name: Build dev Win64 binary
on:
  workflow_dispatch:

jobs:
  build-dev-win64:
    name: Build x64 Windows binary
    runs-on: windows-2019
    env:
      BUILD_ARCH: x64
      BUILD_LOGLEVEL: verbose
      GYP_MSVS_VERSION: '2017'
      GYP_MSVS_OVERRIDE_PATH: 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools'
    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          toolset: 14.16
          vsversion: 2017
      - name: Install VS2017 Build Tools (v141)
        run: choco install visualstudio2017buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.v141.x86.x64" -y
      - uses: MatteoH2O1999/setup-python@v3 # https://github.com/actions/setup-python/issues/672
        with:
          python-version: '2.7'
      - uses: actions/checkout@v3
      - run: npm install --production
      - run: (cd nexe && npm install --production)
      - run: (cd nexe && node build)
      - run: move nexe\nyuu.exe nyuu.exe && 7z a -t7z -mx=9 nyuu.7z config-sample.json nyuu.exe
      - uses: actions/upload-artifact@v4
        with:
          path: ./nyuu.7z
          name: nyuu-${{ github.ref_name }}-win64.7z
          retention-days: 5
